name: Bug Report
description: Report a bug in Steno
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "Thanks for reporting a bug. Please fill out the sections below."
  - type: input
    id: macos-version
    attributes:
      label: macOS Version
      placeholder: "e.g., macOS 14.3"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true
  - type: checkboxes
    id: permissions
    attributes:
      label: Permissions Granted
      options:
        - label: Microphone
        - label: Accessibility
        - label: Input Monitoring
  - type: textarea
    id: logs
    attributes:
      label: Additional Context
      description: Logs, screenshots, or other context
